#!/usr/bin/env bash

printf '{"cmd":"grid","payload":{"rows":%s,"cols":%s}}\n' 2 2 | socat - UNIX-CONNECT:/tmp/basestation-cameras-ipc

# Ensure at least one argument is provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 num1 [num2 ...]"
    exit 1
fi

# Array to store process IDs
pids=()

function cleanup {
  for id in ${pids[@]}; do
	  payload=$(printf '{"cmd":"remove_stream","payload":{"id":"%s"}}\n' $id)
    echo $payload
	  echo $payload | socat - UNIX-CONNECT:/tmp/basestation-cameras-ipc
  done
}

trap cleanup EXIT

# Loop over all command-line arguments
for num in "$@"; do
    echo "Launching command for RTSP address: 192.168.1.${num}"
    url="rtsp://192.168.1.${num}/user=admin&password=&channel=1&stream=0.sdp?"
    id="cam-${num}"
    payload=$(printf '{"cmd":"add_stream","payload":{"id":"%s","url":"%s"}}\n' $id $url)
    echo $payload
    echo $payload | socat - UNIX-CONNECT:/tmp/basestation-cameras-ipc
    # Save the PID of the background process
    pids+=("$id")
done

echo "Press enter to close cameras"
# Wait for all background processes to complete
read
